# HPTA Security Suite Kubernetes Deployment
apiVersion: v1
kind: Namespace
metadata:
  name: hpta-security
---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: hpta-config
  namespace: hpta-security
data:
  FLASK_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "5000"
---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: hpta-secrets
  namespace: hpta-security
type: Opaque
stringData:
  GEMINI_API_KEY: "your-gemini-api-key-here"
  SECRET_KEY: "your-secret-key-here"
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: hpta-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        command:
        - redis-server
        - --appendonly
        - "yes"
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: hpta-security
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
# HPTA App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpta-app
  namespace: hpta-security
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpta-app
  template:
    metadata:
      labels:
        app: hpta-app
    spec:
      containers:
      - name: hpta-security-suite
        image: hpta-security-suite:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: hpta-config
              key: FLASK_ENV
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: hpta-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: hpta-config
              key: PORT
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: hpta-secrets
              key: GEMINI_API_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hpta-secrets
              key: SECRET_KEY
        volumeMounts:
        - name: uploads-data
          mountPath: /app/uploads
        - name: reports-data
          mountPath: /app/reports
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: uploads-data
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: reports-data
        persistentVolumeClaim:
          claimName: reports-pvc
---
# HPTA App Service
apiVersion: v1
kind: Service
metadata:
  name: hpta-app-service
  namespace: hpta-security
spec:
  selector:
    app: hpta-app
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: hpta-security
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: hpta-security
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-pvc
  namespace: hpta-security
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpta-app-hpa
  namespace: hpta-security
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpta-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
