[build]
builder = "nixpacks"

[build.nixpacksConfig]
pythonVersion = "3.11"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
FLASK_ENV = "production"
PYTHONPATH = "/app"
