services:
  - type: web
    name: hpta-security-suite
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      chmod +x build.sh
      ./build.sh
    startCommand: python start_full_backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
