services:
  - type: web
    name: hpta-security-suite
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements_hpta.txt
      chmod +x build.sh || echo "build.sh not found, continuing..."
      ./build.sh || echo "build.sh execution failed, continuing..."
    startCommand: python start_minimal.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
