version: '3.8'

services:
  # Main HPTA Security Suite Application
  hpta-app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: hpta-security-suite
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - uploads_data:/app/uploads
      - reports_data:/app/reports
      - sessions_data:/app/sessions
    networks:
      - hpta-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and session storage  
  redis:
    image: redis:7-alpine
    container_name: hpta-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hpta-network
    command: redis-server --appendonly yes

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: hpta-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - hpta-network
    depends_on:
      - hpta-app

# Persistent volumes for data
volumes:
  uploads_data:
    driver: local
  reports_data:
    driver: local
  sessions_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local

# Network for inter-service communication
networks:
  hpta-network:
    driver: bridge
